{"name": "test_create_courier_existing_login", "status": "failed", "statusDetails": {"message": "AssertionError: assert (409 == 409 and 'Этот логин у...буйте другой.' == 'Этот логин уже используется'\n +  where 409 = <Response [409]>.status_code\n  - Этот логин уже используется\n  + Этот логин уже используется. Попробуйте другой.)", "trace": "self = <tests.test_create_courier.TestCreateCourier object at 0x0000017BAA6D07D0>\n\n    def test_create_courier_existing_login(self):\n        login = DataForTests.existing_user_login\n        password = helper.generate_random_string(10)\n        first_name = helper.generate_random_string(10)\n        payload = {\n            \"login\": login,\n            \"password\": password,\n            \"firstName\": first_name\n        }\n        response = requests.post((Urls.main_site + ApiHandles.create_courier), data=payload)\n>       assert response.status_code == 409 and response.json()[\"message\"] == \"Этот логин уже используется\"\nE       AssertionError: assert (409 == 409 and 'Этот логин у...буйте другой.' == 'Этот логин уже используется'\nE        +  where 409 = <Response [409]>.status_code\nE         - Этот логин уже используется\nE         + Этот логин уже используется. Попробуйте другой.)\n\ntests\\test_create_courier.py:95: AssertionError"}, "start": 1701432366702, "stop": 1701432367231, "uuid": "05c9e9a5-cbea-48b7-81cb-9605b04d813c", "historyId": "fc27c551270bcca6b8ef5d13c94e0d32", "testCaseId": "fc27c551270bcca6b8ef5d13c94e0d32", "fullName": "tests.test_create_courier.TestCreateCourier#test_create_courier_existing_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_courier"}, {"name": "subSuite", "value": "TestCreateCourier"}, {"name": "host", "value": "ARSENIY-PC"}, {"name": "thread", "value": "30136-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_courier"}]}